import type { Config } from 'tailwindcss';
import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

export default {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#f0dbff',
        'secondary-container': '#7900cd',
        secondary: '#ddb7ff',
        'surface-container': '#201f1f',
        'primary-fixed': '#d8e2ff',
        'on-error': '#690005',
        'tertiary-fixed-dim': '#4edea3',
        'surface-container-high': '#2a2a2a',
        'on-surface': '#e5e2e1',
        'on-secondary-fixed-variant': '#6900b3',
        'on-secondary-container': '#ddb7ff',
        'on-primary-fixed': '#001a41',
        'surface-dim': '#131313',
        'surface-container-low': '#1c1b1b',
        surface: '#131313',
        'primary-fixed-dim': '#adc6ff',
        'on-background': '#e5e2e1',
        primary: '#adc6ff',
        'on-tertiary-fixed-variant': '#005236',
        'on-secondary': '#4a0080',
        'surface-bright': '#3a3939',
        'on-tertiary': '#003824',
        'tertiary-container': '#00a572',
        'on-primary-fixed-variant': '#004493',
        tertiary: '#4edea3',
        'on-tertiary-container': '#00311f',
        'inverse-primary': '#005bc1',
        'primary-container': '#4b8eff',
        outline: '#8b90a0',
        background: '#131313',
        'on-secondary-fixed': '#2c0050',
        'surface-container-lowest': '#0e0e0e',
        'tertiary-fixed': '#6ffbbe',
        'surface-variant': '#353534',
        'inverse-surface': '#e5e2e1',
        'on-primary-container': '#00285c',
        'on-primary': '#002e69',
        'on-error-container': '#ffdad6',
        'inverse-on-surface': '#313030',
        'error-container': '#93000a',
        'on-surface-variant': '#c1c6d7',
        'surface-tint': '#adc6ff',
        'outline-variant': '#414755',
        'on-tertiary-fixed': '#002113',
        error: '#ffb4ab',
        'surface-container-highest': '#353534',
        'secondary-fixed-dim': '#ddb7ff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-desktop': '40px',
        unit: '4px',
        'margin-mobile': '16px',
        gutter: '24px',
        'container-max': '1440px',
      },
      fontFamily: {
        'mono-sm': ['Geist', 'monospace'],
        'display-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Geist', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'mono-sm': ['11px', { lineHeight: '1.4', letterSpacing: '0em', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '1.5', letterSpacing: '0em', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '1.6', letterSpacing: '0em', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
      animation: {
        shimmer: 'shimmer 3s infinite',
      },
    },
  },
  plugins: [forms, containerQueries],
} satisfies Config;
